HTTP/1.0 503 Service Unavailable
Cache-Control: no-cache
Connection: close
Content-Type: text/html

<html><body><h1>503 Servicio no disponible</h1>
Nos disculpamos por la no disponibilidad.
</body></html>